# Generated by Django 5.0.6 on 2026-04-27 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_repo_id', models.CharField(help_text='GitHub repository ID — stable across renames', max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('is_private', models.BooleanField(default=False)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('webhook_secret', models.CharField(blank=True, default='', help_text='HMAC secret for validating GitHub webhook payloads', max_length=100)),
                ('webhook_id', models.CharField(blank=True, default='', help_text='GitHub webhook ID — used to manage the webhook via API', max_length=100)),
                ('is_webhook_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
                'db_table': 'repositories',
                'ordering': ['-created_at'],
            },
        ),
    ]
