# Generated by Django 5.0.6 on 2026-04-27 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_pr_number', models.IntegerField()),
                ('github_pr_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True, default='')),
                ('head_branch', models.CharField(max_length=200)),
                ('base_branch', models.CharField(default='main', max_length=200)),
                ('head_sha', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('merged', 'Merged'), ('closed', 'Closed')], db_index=True, default='open', max_length=30)),
                ('github_created_at', models.DateTimeField(blank=True, null=True)),
                ('github_updated_at', models.DateTimeField(blank=True, null=True)),
                ('github_merged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_prs', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='repositories.repository')),
            ],
            options={
                'db_table': 'pull_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('changes_requested', 'Changes Requested'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('approved_count', models.PositiveIntegerField(default=0)),
                ('changes_requested_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cycles', to='reviews.pullrequest')),
            ],
            options={
                'db_table': 'review_cycles',
                'ordering': ['-cycle_number'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('file_path', models.CharField(blank=True, default='', help_text='File path this comment is attached to, e.g. src/auth/views.py', max_length=500)),
                ('line_number', models.PositiveIntegerField(blank=True, help_text='Line number in the file this comment refers to', null=True)),
                ('is_ai_generated', models.BooleanField(db_index=True, default=False, help_text='True if this comment was generated by the AI pre-reviewer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.comment')),
                ('review_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.reviewcycle')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(blank=True, choices=[('approved', 'Approved'), ('changes_requested', 'Changes Requested'), ('commented', 'Commented')], default='', max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_assignments', to='reviews.reviewcycle')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviewer_assignments',
            },
        ),
        migrations.AddField(
            model_name='reviewcycle',
            name='reviewers',
            field=models.ManyToManyField(related_name='assigned_cycles', through='reviews.ReviewerAssignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='pullrequest',
            constraint=models.UniqueConstraint(fields=('repository', 'github_pr_number'), name='unique_pr_per_repo'),
        ),
        migrations.AddConstraint(
            model_name='reviewerassignment',
            constraint=models.UniqueConstraint(fields=('review_cycle', 'reviewer'), name='unique_reviewer_per_cycle'),
        ),
        migrations.AddConstraint(
            model_name='reviewcycle',
            constraint=models.UniqueConstraint(fields=('pull_request', 'cycle_number'), name='unique_cycle_per_pr'),
        ),
    ]
